# Generated by Django 5.2.1 on 2025-06-29 18:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_user_auth_api_us_email_c29b6b_idx_and_more'),
        ('cart', '0001_initial'),
        ('product', '0002_product_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cart_item_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shipping_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('round_of_val', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('can_cod', models.CharField(blank=True, max_length=3, null=True)),
                ('total_items', models.IntegerField(blank=True, null=True)),
                ('total_quantity', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('currency', models.CharField(blank=True, default='INR', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Order Summary',
                'verbose_name_plural': 'Order Summaries',
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='cart_cart_user_id_b645f9_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='cart_cartit_cart_id_4fb076_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product'], name='cart_cartit_product_985dba_idx'),
        ),
        migrations.AddIndex(
            model_name='ordersummary',
            index=models.Index(fields=['cart_amount'], name='cart_orders_cart_am_9d357b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordersummary',
            index=models.Index(fields=['cart_item_discount'], name='cart_orders_cart_it_538e7c_idx'),
        ),
    ]
